name: Swift CI

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
   
    - name: Set up Swift
      uses: actions/checkout@v3
      with:
        swift-version: '5.9' 
        
    - name: Build project
      run: swift build -v
      
  
