name: Swift CI

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Swift
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: '5.9' # Specify the Swift version
        
    - name: Build project
      run: swift build -v
      
  
